[package]
name = "cargo-hatch"
version = "0.1.2"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
rust-version = "1.56"
license = "AGPL-3.0-only"
readme = "README.md"
description = "Hatch new projects like a chick coming out of its egg."
homepage = "https://github.com/dnaka91/cargo-hatch"
repository = "https://github.com/dnaka91/cargo-hatch"
categories = ["development-tools", "development-tools::cargo-plugins"]
keywords = ["cargo", "cargo-subcommand", "cli", "crates", "template"]
include = ["tests/**/*", "src/**/*", "LICENSE", "README.md"]

[dependencies]
anyhow = "1.0.44"
camino = { version = "1.0.5", features = ["serde1"] }
crossterm = "0.22.1"
directories-next = "2.0.0"
git2 = "0.13.23"
ignore = "0.4.18"
indexmap = { version = "1.7.0", features = ["serde-1"] }
mime_guess = "2.0.3"
num-traits = "0.2.14"
serde = { version = "1.0.130", features = ["derive"] }
structopt = "0.3.25"
tera = "1.13.0"
thiserror = "1.0.30"
toml = "0.5.8"

[dev-dependencies]
dir-diff = "0.3.2"
tempfile = "3.2.0"

[profile.release]
lto = true
