[package]
name = "{{ project_name }}"
authors = ["{{ git_author }}"]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.44"
axum = "0.2.8"
tokio = { version = "1.12.0", features = ["macros", "rt"] }
tracing = "0.1.29"
tracing-subscriber = "0.2.25"
